backend:
  name: git-gateway
  branch: main
  # name: test-repo
media_folder: public/img
public_folder: img
collections:
  - label: "Blog Posts"
    name: "posts"
    folder: "public/data/posts"
    create: true
    identifier_field: "title"
    slug: "{{fields.slug}}"
    format: "json"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string",pattern: ['^[a-zA-Z0-9-_]+$', "Alphanumeric with dashes or underscores"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "coverImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "pages"
    label: "Pages"
    files:
    - file: "public/data/about/bio.md"
      label: "About"
      name: "about"
      fields:
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Bio", name: "bio", widget: "markdown"}
        - {label: "Profile Image", name: "profileImage", widget: "image", required: true}
      
    - file: "public/data/about/home.md"
      label: "Home"
      name: "home"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Subtitle", name: "subtitle", widget: "string"}
      
    